/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/setuptools/config/__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.parse_configuration` became deprecated.

For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the future.

  warnings.warn(dedent(msg), SetuptoolsDeprecationWarning)
In file included from /project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948,
                 from /project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from panel.c:698:
/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
panel.c: In function '__pyx_pf_5panel_2sdf_vectorized_stl.constprop':
panel.c:9207:17: warning: '__pyx_v_se' may be used uninitialized in this function [-Wmaybe-uninitialized]
 9207 |     __pyx_t_4 = PyFloat_FromDouble(__pyx_v_s); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 244, __pyx_L1_error)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
USER WARNING: In order to avoid a segmentation fault, you need to have supplied the 'f' flag to the triangleOptions input.
USER WARNING: In order to avoid an edge assertion error, you need to have supplied the 'ee' flag to the triangleOptions input.
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    with open(stl_file,'r') as f: # for reading ship stl
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    dispatch(ns.calculateSolution,
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
slurmstepd: error: Detected 1 oom_kill event in StepId=195986.0. Some of the step tasks have been OOM Killed.
srun: error: mike065: task 12: Out Of Memory
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    with open(stl_file,'r') as f: # for reading ship stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    with open(stl_file,'r') as f: # for reading ship stl
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    dispatch(ns.calculateSolution,
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    with open(stl_file,'r') as f: # for reading ship stl
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 712, in attachModels
    self.particle_sdfList[0](t, np.reshape(self.mesh.nodeArray, (self.mesh.nodeArray.size//3,3)),
  File "panel.pyx", line 90, in panel.sdf_vectorized_stl
    with open(stl_file,'r') as f: # for reading ship stl
FileNotFoundError: [Errno 2] No such file or directory: 'single_stand_panel.stl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/cekees/cekees/proteus/fct/bin/parun", line 583, in <module>
    dispatch(ns.calculateSolution,
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Profiling.py", line 198, in __call__
    return func(*func_args, **func_kwargs)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/NumericalSolution.py", line 518, in calculateSolution
    m.attachModels(self.modelList)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/Transport.py", line 6776, in attachModels
    m.coefficients.attachModels(models)
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 725, in attachModels
    sdf_at_node, sdNormals = sdf(self.mesh.nodeArray[j, :])
  File "/ddnA/project/cekees/cekees/proteus/fct/lib/python3.10/site-packages/proteus/mprans/RANS2P.py", line 723, in <lambda>
    sdf = lambda x: self.particle_sdfList[i](t, x)
  File "panel.pyx", line 88, in panel.sdf_vectorized_stl
    def sdf_vectorized_stl(double t, np.ndarray x, np.ndarray phi):
TypeError: sdf_vectorized_stl() takes exactly 3 positional arguments (2 given)
srun: Job step aborted: Waiting up to 302 seconds for job step to finish.
slurmstepd: error: *** STEP 195986.0 ON mike065 CANCELLED AT 2024-01-25T12:14:25 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 195986 ON mike065 CANCELLED AT 2024-01-25T12:14:25 DUE TO TIME LIMIT ***
